services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b 0.0.0.0"
    ports:
      - "3000:3000"
      - "3001:3001"
    environment:
      RAILS_ENV: test
      NODE_OPTIONS: --openssl-legacy-provider
      CAPYBARA_SERVER_HOST: 0.0.0.0
      CAPYBARA_SERVER_PORT: 3001
      CAPYBARA_APP_HOST: http://web:3001
    depends_on:
      - db
      - chrome
    networks:
      - ci_network

  chrome:
    image: selenium/standalone-chromium:latest
    ports:
      - "4444:4444"
    networks:
      - ci_network

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: test_db
    ports:
      - "3306:3306"
    networks:
      - ci_network

networks:
  ci_network:
